name: Test LanguageTool Setup Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Homebrew (if not available)
      - name: Install Homebrew
        run: |
          if ! command -v brew &>/dev/null; then
            echo "Homebrew not found. Installing..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      # Step 3: Install Java (OpenJDK 17)
      - name: Install Java
        run: |
          brew install openjdk@17
          sudo ln -sfn /usr/local/opt/openjdk@17/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk

      # Step 4: Run install-languagetool.sh to test installation
      - name: Test install-languagetool.sh script
        run: |
          chmod +x ./install-languagetool.sh
          ./install-languagetool.sh --version 6.6

      # Step 5: Verify if LanguageTool is running
      - name: Verify LanguageTool server is running
        run: |
          curl -s http://localhost:8081 || exit 1  # Exit with error if server is not running

      # Step 6: Test uninstall-languagetool.sh script
      - name: Test uninstall-languagetool.sh script
        run: |
          chmod +x ./uninstall-languagetool.sh
          ./uninstall-languagetool.sh

      # Step 7: Clean up any leftovers after uninstallation
      - name: Clean up leftovers
        run: |
          rm -rf ~/.languagetool
          rm -f ~/Library/LaunchAgents/org.languagetool.server.plist
          rm -f /tmp/languagetool.out /tmp/languagetool.err
