name: Test LanguageTool Setup Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Homebrew (if not available)
      - name: Install Homebrew
        run: |
          if ! command -v brew &>/dev/null; then
            echo "Homebrew not found. Installing..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          # Verify Homebrew installation
          if ! command -v brew &>/dev/null; then
            echo "Homebrew installation failed!"
            exit 1
          fi
          echo "Homebrew successfully installed."

      # Step 3: Install Java (OpenJDK 17)
      - name: Install Java
        run: |
          brew install openjdk@17
          sudo ln -sfn /usr/local/opt/openjdk@17/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk
          # Verify Java installation
          if ! java -version &>/dev/null; then
            echo "Java installation failed!"
            exit 1
          fi
          echo "Java successfully installed."

      # Step 4: Run install-languagetool.sh to test installation
      - name: Test install-languagetool.sh script
        run: |
          chmod +x ./install-languagetool.sh
          ./install-languagetool.sh --version 6.6

      # Step 5: Verify if LanguageTool server is running
      - name: Verify LanguageTool server is running
        run: |
          curl -X POST http://localhost:8081/v2/check \
            -d "text=Hello world" \
            -d "language=en-US" \
            -H "Content-Type: application/x-www-form-urlencoded" || exit 1  # Exit with error if server is not running

      # Step 6: Stop any existing LanguageTool server
      - name: Stop any existing LanguageTool server
        run: |
          pkill -f languagetool-server.jar || true

      # Step 7: Restart LanguageTool server
      - name: Restart LanguageTool server
        run: |
          LANGUAGETOOL_SERVER_JAR="$HOME/.languagetool/LanguageTool-6.6/languagetool-server.jar"
          nohup java -jar $LANGUAGETOOL_SERVER_JAR --port 8081 > /dev/null 2>&1 &
          echo "LanguageTool server started at http://localhost:8081"

      # Step 8: Ensure LanguageTool server is running after restart
      - name: Ensure LanguageTool server is running
        run: |
          curl -s http://localhost:8081/v2/check || exit 1

      # Step 9: Test uninstall-languagetool.sh script
      - name: Test uninstall-languagetool.sh script
        run: |
          chmod +x ./uninstall-languagetool.sh
          ./uninstall-languagetool.sh --force

      # Step 10: Clean up leftovers
      - name: Clean up leftovers
        run: |
          rm -rf ~/.languagetool
          rm -f ~/Library/LaunchAgents/org.languagetool.server.plist
          rm -f /tmp/languagetool.out /tmp/languagetool.err
          rm -f /tmp/languagetool.log
          echo "Cleaned up leftovers."
